<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{851d153b-ef72-434d-b1dc-408dc36f46e2}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fb05D100 : IO.FB_O5D100;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fb05D100();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>